name: "godot-ci build-and-release"

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  GODOT_VERSION: 4.5.1
  EXPORT_NAME: gamejam2025
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: GitHub Tag Name
        run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
         
      - name: Setup folders
        run: |
          mkdir -p .godot/editor .godot/imported
          mkdir -p build/web
          mkdir -p build/windows
          mkdir -p build/linux
          mkdir -p build/mac
          echo "$GITHUB_REF" > build/version.txt

      - name: Web Build
        run: |
          EXPORT_DIR="$(pwd)/build"
          godot -v --headless --export-release "Web" "$EXPORT_DIR/web/index.html"

      - name: Windows Build
        run: |
          EXPORT_DIR="$(pwd)/build"
          godot -v --headless --export-release "Windows Desktop" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"

      - name: Linux Build
        run: |
          EXPORT_DIR="$(pwd)/build"
          godot -v --headless --export-release "Linux" "$EXPORT_DIR/linux/$EXPORT_NAME.x86_64"

      - name: Mac Build
        run: |
          EXPORT_DIR="$(pwd)/build"
          godot -v --headless --export-release "macOS" "$EXPORT_DIR/mac/$EXPORT_NAME.zip"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-builds
          path: build
  release-itchio:
    name: To itchio
    needs: build  
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.5.1
    steps:
      - name: Download build 
        uses: actions/download-artifact@v4
        with:
          name: my-builds
      - name: Listar archivos en la carpeta
        run: |
          ls
      - name: Upload bundles
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
        run: |
          echo $GITHUB_REF_NAME
          butler push web $ITCH_USER/$ITCH_GAME:html5 --userversion $GITHUB_REF_NAME
          butler push windows $ITCH_USER/$ITCH_GAME:windows --userversion $GITHUB_REF_NAME
          butler push linux $ITCH_USER/$ITCH_GAME:linux --userversion $GITHUB_REF_NAME
          butler push mac $ITCH_USER/$ITCH_GAME:mac --userversion $GITHUB_REF_NAME
